<?php
/**
 * @file
 * Code for the SiteNow SEO feature.
 */

include_once 'sitenow_seo.features.inc';


/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_seo_form_googleanalytics_admin_settings_form_alter(&$form, &$form_state, $form_id) {

  // turn on caching of tracking code
  $form['advanced']['googleanalytics_cache']['#default_value'] = 1;
  // remove unwanted options for non admins
  if (!user_access('administer modules')) {
    $form['tracking_title']['#access'] = FALSE;
    $form['tracking']['domain_tracking']['#access'] = FALSE;
    $form['tracking']['page_vis_settings']['#access'] = FALSE;
    $form['tracking']['role_vis_settings']['#access'] = FALSE;
    $form['tracking']['user_vis_settings']['#access'] = FALSE;
    $form['tracking']['user_vis_settings']['#access'] = FALSE;
    $form['tracking']['linktracking']['#access'] = FALSE;
    $form['tracking']['messagetracking']['#access'] = FALSE;
    $form['tracking']['search_and_advertising']['#access'] = FALSE;
    $form['tracking']['privacy']['#access'] = FALSE;
    $form['googleanalytics_custom_var']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_seo_form_xmlsitemap_settings_form_alter(&$form, &$form_state, $form_id) {
  // Remove unwanted options for non admins at admin/config/search/xmlsitemap/settings.
  if (!user_access('administer modules')) {
    $form['xmlsitemap_xsl']['#access'] = FALSE;
    $form['xmlsitemap_prefetch_aliases']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
  }
}
